version: "3.1"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DATABASE: ${DATABASE_NAME}
    volumes:
      - /docker-data/${DATABASE_NAME}:/var/lib/postgresql/data
    ports:
      - 5432:5432
      - 54321:54321
